# Use root/example as user/password credentials
version: "3.8"

services:
  mymongodb:
    image: mongo:7.0
    restart: always
    container_name: mongo-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: local_library
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks: 
      - mongo1_network
    ports: 
      - 27017:27017

  mongo-express:
    image: mongo-express:1.0-20-alpine3.18
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: example
      ME_CONFIG_MONGODB_AUTH_DATABASE: local_library
      MONGODB_CONNSTRING: mongodb://root:example@mymongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mymongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mymongodb:27017/
      ME_CONFIG_MONGODB_PORT: 27017
#     ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
    networks: 
      - mongo1_network 
  
    depends_on:
      - mymongodb

networks:
  mongo1_network:
    driver: bridge
